// import type { Metadata } from 'next';
// import './globals.css';
// import Footer from './ui/Footer';

// export const metadata: Metadata = {
// 	title: 'Create Next App',
// 	description: 'Generated by create next app',
// };

// export default function RootLayout({
// 	children,
// }: Readonly<{
// 	children: React.ReactNode;
// }>) {
// 	return (
// 		<html lang='en'>
// 			<body>
// 				<>
// 					{children}
// 					<Footer />
// 				</>
// 			</body>
// 		</html>
// 	);
// }

import type { Metadata } from 'next';
import './globals.css';
import Footer from './ui/Footer';

export const metadata: Metadata = {
  title: 'StarDock UI Library',
  description: 'A beautiful, flexible UI component library built for modern web apps.',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}


